### ISSUE TITLE
use of requestAnimationFrame over setInterval

### ISSUE THREAD

**Issue by thelegendski** [vExcess/Drawlite#1]
Drawlite [currently uses](https://github.com/vExcess/Drawlite/blob/f2dca40a079926d55bb93bd694ea94d6cdaf644f/drawlite-0.0.2.js#L543) `setInterval` an' i believe that it is for Drawlite's benefit that you employ the `requestAnimationFrame` method instead.

`setInterval` is not consistent at its ability to maintain the target fps. on the other hand, `requestAnimationFrame` is much more consistent at maintainin' the target fps an' produces higher quality animation without the bugs of `setInterval`. refer to [this](https://stackoverflow.com/questions/38709923/why-is-requestanimationframe-better-than-setinterval-or-settimeout) SO article for more details.

to see `requestAnimationFrame` used in a canvas library compatible with KA [which i assume would be one of the purposes of this project] an' beyond, please refer to [lines](https://github.com/thelegendski/ski.js/blob/cbe1871ad63258ed0d8dfcc4d3cf60188f532817/main.js#L482) 482 to 505 in ski.js.

**Comment by vExcess** [comment]
I've never had any issues with setInterval except for one time when using Babylon.js
From my understanding setInterval always tries to execute every n seconds
requestAnimationFrame on the other hand always tries to create a smooth animation (even if getting a smoother animation means plumetting from 60 to 30 FPS) with a speed cap of the refresh rate of the user's monitor
But with requestAnimationFrame you can't control the FPS which is big sad.

**Comment by thelegendski** [comment]
@vExcess 
that may owe to your browser's JS engine or your comp itself.

you can control the FPS with general ease. it's exemplified in ski.js, but i can reproduce here if you would prefer it that way. the method itself is not unique an' can be found elsewhere on the web. not as simple, but much more efficient an' beneficial for the user of Drawlite.
```
let raf = time => {
	requestAnimationFrame(raf)
	var delta = time - then
	var ms = 1000 / data.rate
	if (delta < ms)
		return
	const overflow = delta % ms
	const then = time - overflow
	delta -= overflow
        //implement the draw function here
	draw(time)
	data.millis = performance.now() - data.start
}
requestAnimationFrame(raf)
```

**Comment by vExcess** [comment]
Having a function run when it doesn't need to is more efficient? 🤔

**Comment by thelegendski** [comment]
you'd need to have it only trigger when the draw function actually exists which was the hard part with ski.js. PT an' i finally figured it out, but it's not easy if you don't already have the solution.

**Comment by vExcess** [comment]
I feel like you could just do `typeof draw === "function"` then it's defined

**Comment by thelegendski** [comment]
you could try, but KA's live editor doesn't make the most sense lol.

**Comment by vExcess** [comment]
I made `frameRate(NATIVE);` where `NATIVE = 0; ` now runs using requestAnimationFrame. 
On a side note: thanks for getting my KA account banned after I advocated for your account being unbanned. Twas a kind thought.

**Comment by thelegendski** [comment]
closin' the issue.

you are mighty welcome.
